### ISSUE TITLE
The future of generator-ghost

### ISSUE THREAD

**Issue by acburdine** [TryGhost/generator-ghost#14]
Ghost 1.0 was officially released today 🎉 

With the release of ghost 1.0 comes ghost-cli - a command line tool for automatically installing and updating Ghost. ghost-cli's functionality I think makes what's in this generator somewhat obsolete; however, there are some newer concepts being introduced into Ghost that I think this generator could be made useful for:

- [ ] Basic theme scaffolding
- [ ] Ghost storage adapters
- [ ] Ghost scheduling adapters
- [ ] Ghost-CLI extensions

It would essentially remove the ability of this generator to actually install Ghost itself and instead just generate basic scaffolding for various Ghost extensions (and maybe apps in the future).

Any thoughts?

**Comment by sethvincent** [comment]
Hey! I haven't used this in a long time. I'd be happy to transfer it to your profile, and in general, feel free to take this in a different direction or retire it based on the new ghost-cli.

**Comment by acburdine** [comment]
If you want to do that then sure 😄

**Comment by sethvincent** [comment]
Cool! You'll have to delete your fork first.

**Comment by acburdine** [comment]
done!

**Comment by sethvincent** [comment]
Nice! Transfer complete. Thanks @acburdine.

**Comment by acburdine** [comment]
@sethvincent sorry to bug you again - I noticed today that generator-ghost on npm is still owned by you - would you mind transferring the npm ownership as well?

We (the ghost core team) are wanting to start using it as part of Ghost-CLI to generate various things.

**Comment by acburdine** [comment]
Gonna go ahead and close this issue - I'm working on some refactoring atm and will open new issues for the individual new things as they get worked on/needed 😄
